//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionRestaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public int Id_reservation { get; set; }
        public System.DateTime Date_reservation { get; set; }
        public int Id_utilisateur { get; set; }
        public int Id_table { get; set; }
    
        public virtual TABLE_RESTAURANT TABLE_RESTAURANT { get; set; }
        public virtual UTILISATEUR UTILISATEUR { get; set; }
    }
}
